# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ankle_joint:
    has_velocity_limits: true
    max_velocity: 0.265
    has_acceleration_limits: false
    max_acceleration: 0
  hip_joint:
    has_velocity_limits: true
    max_velocity: 0.375
    has_acceleration_limits: false
    max_acceleration: 0
  knee_joint:
    has_velocity_limits: true
    max_velocity: 0.539
    has_acceleration_limits: false
    max_acceleration: 0